export * from './product-Images-slider'
export * from './product-specification'
export * from './socialMedia-share'
export * from './productTabsContent/productDescription'
export * from './rating-card'
export * from './rating'
export *  from './cards'
export *  from './productTabsContent'